from __future__ import annotations
"""
InsightEngine AI - Cleaning Reason Engine
============================================
Generates 100% deterministic, evidence-based explanations for
every cleaning action.

Design principle:
  Every sentence is constructed from MEASURED numbers in the profiling
  report — never inferred, never generated by an LLM.
  The same profiling data always produces the same explanation.

Each action gets three fields:
  why         — the core reason (evidence-based, 1 sentence)
  risk        — what would happen WITHOUT this fix (1 sentence)
  method_why  — why THIS specific method/value was chosen (1 sentence)

These three together give a non-technical business user full
understanding of every decision without requiring data science knowledge.
"""
import math
import logging
from typing import Optional

logger = logging.getLogger(__name__)


class ReasonEngine:
    """
    Pure rule-based engine. No LLM. No randomness.
    Input: action dict + profiling report + execution context
    Output: dict with why / risk / method_why
    """

    def explain(
        self,
        action: dict,
        profiling_report: dict,
        execution_context: Optional[dict] = None,
    ) -> dict:
        """
        Generate a full explanation for one cleaning action.

        Args:
            action:             The cleaning action dict (action, column, method, …)
            profiling_report:   Full profiler output for the RAW dataset
            execution_context:  Optional dict with actual runtime values:
                                  fill_value, rows_removed, actual_count, etc.

        Returns:
            dict with why, risk, method_why, severity, evidence_numbers
        """
        ctx = execution_context or {}
        atype = action.get("action", "")

        dispatch = {
            "fill_missing":      self._explain_fill_missing,
            "remove_duplicates": self._explain_remove_duplicates,
            "drop_column":       self._explain_drop_column,
            "fix_dtype":         self._explain_fix_dtype,
            "cap_outliers":      self._explain_cap_outliers,
            "drop_missing_rows": self._explain_drop_missing_rows,
        }

        handler = dispatch.get(atype)
        if not handler:
            return {
                "why":        f"This action ({atype}) was applied as part of standard data preparation.",
                "risk":       "Skipping it may cause unexpected errors during analysis.",
                "method_why": "",
                "severity":   "low",
                "evidence_numbers": {},
            }

        try:
            result = handler(action, profiling_report, ctx)
            result.setdefault("severity", "medium")
            result.setdefault("evidence_numbers", {})
            return result
        except Exception as e:
            logger.warning(f"ReasonEngine failed for action {atype}: {e}")
            return {
                "why":        "This fix was applied based on data quality analysis.",
                "risk":       "Skipping it could affect analysis accuracy.",
                "method_why": "",
                "severity":   "low",
                "evidence_numbers": {},
            }

    # ─── Per-action explainers ────────────────────────────────────────────────

    def _explain_fill_missing(
        self, action: dict, profiling: dict, ctx: dict
    ) -> dict:
        col = action["column"]
        method = action.get("method", "median")
        fill_value = ctx.get("fill_value")          # actual value used at runtime
        total_rows = profiling.get("total_rows", 0)

        miss = profiling.get("missing_values", {}).get(col, {})
        count = miss.get("count", ctx.get("actual_count", 0))
        pct   = miss.get("percentage", round(count / total_rows * 100, 1) if total_rows else 0)
        dtype = miss.get("dtype", "unknown")

        is_numeric = any(t in dtype for t in ("int", "float"))
        severity = "high" if pct > 20 else "medium" if pct > 5 else "low"

        # ── WHY ──────────────────────────────────────────────────────────────
        why = (
            f"Column '{col}' had {count:,} missing values "
            f"({pct}% of {total_rows:,} rows) — "
            f"any calculation using this column would silently ignore those rows."
        )

        # ── RISK (without this fix) ───────────────────────────────────────────
        if is_numeric:
            risk = (
                f"Without this fix, totals, averages, and comparisons on '{col}' "
                f"would be based on only {total_rows - count:,} rows instead of "
                f"{total_rows:,}, giving misleadingly low figures."
            )
        else:
            risk = (
                f"Without this fix, grouping or filtering by '{col}' would "
                f"silently exclude {count:,} rows from every result, making "
                f"category breakdowns look incomplete."
            )

        # ── METHOD WHY ────────────────────────────────────────────────────────
        method_explanations = {
            "median": (
                f"The typical (middle) value was used rather than the average "
                f"because the median is unaffected by unusually high or low values "
                f"in '{col}', making it a safer default for business data."
            ),
            "mean": (
                f"The average value of '{col}' was used to fill gaps, "
                f"which is appropriate when the data has no extreme outliers "
                f"that would distort the average."
            ),
            "mode": (
                f"The most frequently occurring value in '{col}' was used, "
                f"since for categories and labels the most common value is the "
                f"best neutral default — it doesn't introduce a value that doesn't exist."
            ),
            "zero": (
                f"Zero was used as the fill value for '{col}' because missing "
                f"numeric entries in this context most likely represent 'none' "
                f"or 'not applicable', not an unknown value."
            ),
            "ffill": (
                f"Each missing value in '{col}' was filled with the value from "
                f"the previous row, which is the standard approach for time-ordered "
                f"data where the last known value is the best estimate."
            ),
            "bfill": (
                f"Each missing value in '{col}' was filled with the value from "
                f"the next row, suitable when a future known value is a better "
                f"estimate than a past one."
            ),
            "drop": (
                f"Rows where '{col}' was missing were removed entirely because "
                f"this column is essential for analysis — a row without it "
                f"cannot contribute meaningful results."
            ),
        }
        method_why = method_explanations.get(
            method,
            f"The chosen fill method '{method}' was applied to '{col}'."
        )

        # Append the actual fill value if we have it
        if fill_value is not None and method not in ("ffill", "bfill", "drop"):
            fv = f"{fill_value:,.2f}" if isinstance(fill_value, float) else str(fill_value)
            method_why += f" The value used was: {fv}."

        return {
            "why": why,
            "risk": risk,
            "method_why": method_why,
            "severity": severity,
            "evidence_numbers": {
                "missing_count": count,
                "missing_pct": pct,
                "total_rows": total_rows,
                "fill_value": fill_value,
                "method": method,
            },
        }

    def _explain_remove_duplicates(
        self, action: dict, profiling: dict, ctx: dict
    ) -> dict:
        dupes = profiling.get("duplicates", {})
        count = dupes.get("count", ctx.get("rows_removed", 0))
        pct   = dupes.get("percentage", 0)
        total = profiling.get("total_rows", 0)

        severity = "high" if pct > 10 else "medium" if pct > 2 else "low"

        why = (
            f"The dataset contained {count:,} rows that were exact copies of "
            f"another row ({pct}% of {total:,} rows). "
            f"Duplicate rows are a strong signal of a data import or merge error."
        )

        risk = (
            f"Without removing them, every metric — totals, counts, averages — "
            f"would be inflated by {pct}%. "
            f"For example, a total revenue figure would be overstated by "
            f"the revenue of those {count:,} duplicate transactions."
        )

        method_why = (
            "All exact duplicate rows were removed, keeping the first occurrence. "
            "Only rows where every single column is identical are removed — "
            "rows that merely look similar but differ in any field are kept."
        )

        return {
            "why": why,
            "risk": risk,
            "method_why": method_why,
            "severity": severity,
            "evidence_numbers": {
                "duplicate_count": count,
                "duplicate_pct": pct,
                "total_rows": total,
            },
        }

    def _explain_drop_column(
        self, action: dict, profiling: dict, ctx: dict
    ) -> dict:
        col   = action["column"]
        total = profiling.get("total_rows", 0)

        miss = profiling.get("missing_values", {}).get(col, {})
        count = miss.get("count", 0)
        pct   = miss.get("percentage", 0)

        # Check if it was a constant column
        is_constant = col in profiling.get("constant_columns", [])

        if is_constant:
            why = (
                f"Column '{col}' had the same value in every single row. "
                f"A column with no variation provides no information and "
                f"cannot help distinguish between records."
            )
            risk = (
                f"Keeping '{col}' would add noise to any pattern-finding analysis "
                f"without adding any useful signal — it can cause misleading "
                f"correlations with other columns."
            )
            method_why = (
                "The column was removed entirely. No data is lost because "
                "a constant value can always be noted in documentation "
                "if it is needed for context."
            )
            severity = "low"
        else:
            severity = "high" if pct > 50 else "medium"
            why = (
                f"Column '{col}' was missing {count:,} of its {total:,} values "
                f"({pct}% missing). When more than half the values are absent, "
                f"the column cannot be reliably used for analysis."
            )
            risk = (
                f"Keeping a {pct}%-empty column and filling it would mean "
                f"that most of the values in '{col}' are fabricated estimates, "
                f"not real measurements — this would corrupt any conclusion "
                f"that depends on '{col}'."
            )
            method_why = (
                f"The column was removed rather than filled because with "
                f"{pct}% missing, any fill method would be guessing for more "
                f"than half the rows. It is safer to exclude the column entirely "
                f"than to build analysis on largely invented data."
            )

        return {
            "why": why,
            "risk": risk,
            "method_why": method_why,
            "severity": severity,
            "evidence_numbers": {
                "missing_count": count,
                "missing_pct": pct,
                "total_rows": total,
                "is_constant": is_constant,
            },
        }

    def _explain_fix_dtype(
        self, action: dict, profiling: dict, ctx: dict
    ) -> dict:
        col    = action["column"]
        target = action.get("target_type", "numeric")

        type_issues = profiling.get("type_issues", {}).get(col, {})
        current_type = type_issues.get("current_type", "text")
        likely_type  = type_issues.get("likely_type", target)
        total = profiling.get("total_rows", 0)

        TYPE_NAMES = {
            "numeric":  "number",
            "datetime": "date",
            "string":   "text",
            "object":   "text",
        }
        current_name = TYPE_NAMES.get(current_type, current_type)
        target_name  = TYPE_NAMES.get(target, target)

        if target == "numeric":
            why = (
                f"Column '{col}' contained numbers but was stored as text. "
                f"For example, '1,250' or ' 99.5 ' are text values — "
                f"the system cannot add, average, or compare them until "
                f"they are converted to actual numbers."
            )
            risk = (
                f"Without this fix, any formula or calculation on '{col}' "
                f"would either fail with an error or silently produce wrong "
                f"results. Sorting would sort alphabetically ('9' before '10') "
                f"instead of numerically."
            )
            method_why = (
                f"Each value in '{col}' was parsed and converted to a number. "
                f"Values that could not be converted (e.g. text like 'N/A') "
                f"were set to missing and handled by the fill step."
            )

        elif target == "datetime":
            why = (
                f"Column '{col}' contains dates or timestamps stored as plain text. "
                f"As text, the system cannot calculate time differences, "
                f"sort chronologically, or group by month/year."
            )
            risk = (
                f"Without this fix, any time-based analysis on '{col}' — "
                f"trends, seasonality, duration calculations — would "
                f"be impossible or give incorrect results."
            )
            method_why = (
                f"Each value in '{col}' was parsed into a standardised date format. "
                f"Common formats (DD/MM/YYYY, YYYY-MM-DD, etc.) are detected "
                f"automatically. Values that don't match any date pattern "
                f"are set to missing."
            )

        else:
            why = (
                f"Column '{col}' had a data type of '{current_name}' but "
                f"its values are consistently '{target_name}'. "
                f"Mismatched types prevent accurate analysis."
            )
            risk = (
                f"Keeping the wrong type on '{col}' would cause incorrect "
                f"sorting, failed calculations, or misleading groupings."
            )
            method_why = (
                f"'{col}' was converted from {current_name} to {target_name} "
                f"to match the actual nature of its data."
            )

        return {
            "why": why,
            "risk": risk,
            "method_why": method_why,
            "severity": "high",
            "evidence_numbers": {
                "column": col,
                "from_type": current_name,
                "to_type": target_name,
                "total_rows": total,
            },
        }

    def _explain_cap_outliers(
        self, action: dict, profiling: dict, ctx: dict
    ) -> dict:
        col   = action["column"]
        lower = action.get("lower")
        upper = action.get("upper")

        outlier_info = profiling.get("outliers", {}).get(col, {})
        count    = outlier_info.get("count", ctx.get("actual_count", 0))
        pct      = outlier_info.get("percentage", 0)
        min_val  = outlier_info.get("min_value")
        max_val  = outlier_info.get("max_value")
        iqr_lo   = outlier_info.get("lower_bound")
        iqr_hi   = outlier_info.get("upper_bound")
        total    = profiling.get("total_rows", 0)

        severity = "high" if pct > 5 else "medium" if pct > 1 else "low"

        # Build evidence string from actual numbers
        range_str = ""
        if min_val is not None and max_val is not None:
            range_str = f" (actual data range: {min_val:,.2f} to {max_val:,.2f})"

        bounds_str = ""
        if iqr_lo is not None and iqr_hi is not None:
            bounds_str = (
                f" The expected normal range for '{col}' is "
                f"{iqr_lo:,.2f} to {iqr_hi:,.2f} (calculated using the "
                f"interquartile range method)."
            )

        cap_str = ""
        if lower is not None and upper is not None:
            cap_str = f" to the range {lower:,.2f} – {upper:,.2f}"
        elif upper is not None:
            cap_str = f" at a maximum of {upper:,.2f}"
        elif lower is not None:
            cap_str = f" at a minimum of {lower:,.2f}"

        why = (
            f"Column '{col}' had {count:,} extreme values ({pct}% of rows){range_str} "
            f"that fell far outside the normal range for this data.{bounds_str}"
        )

        risk = (
            f"Extreme values in '{col}' would heavily distort averages and totals. "
            f"For instance, a single data entry error of 1,000,000 in a salary column "
            f"can move the company-wide average salary by thousands of pounds, "
            f"leading to wrong budget decisions."
        )

        method_why = (
            f"Extreme values were capped{cap_str} rather than removed entirely. "
            f"Capping (also called Winsorising) keeps the row in the dataset "
            f"— only the single extreme value is adjusted to the boundary. "
            f"This preserves the data point while eliminating its distorting effect."
        )

        return {
            "why": why,
            "risk": risk,
            "method_why": method_why,
            "severity": severity,
            "evidence_numbers": {
                "outlier_count": count,
                "outlier_pct": pct,
                "normal_range_low": iqr_lo,
                "normal_range_high": iqr_hi,
                "cap_lower": lower,
                "cap_upper": upper,
                "total_rows": total,
            },
        }

    def _explain_drop_missing_rows(
        self, action: dict, profiling: dict, ctx: dict
    ) -> dict:
        col       = action.get("column")
        threshold = action.get("threshold")
        total     = profiling.get("total_rows", 0)

        if col:
            miss  = profiling.get("missing_values", {}).get(col, {})
            count = miss.get("count", ctx.get("rows_removed", 0))
            pct   = miss.get("percentage", 0)

            why = (
                f"Rows where '{col}' was completely empty were removed. "
                f"'{col}' is a required field — {count:,} rows ({pct}% of the "
                f"dataset) had no value here and cannot be used for analysis."
            )
            risk = (
                f"Keeping rows with no '{col}' value would mean that any "
                f"analysis grouped or filtered by '{col}' silently includes "
                f"undefined records, producing counts and totals that don't "
                f"correspond to any real business entity."
            )
            method_why = (
                f"The entire row is removed when '{col}' is missing because "
                f"filling in a made-up value for a key identifier would be "
                f"worse than simply not having the row — it would invent data."
            )
            severity = "high" if pct > 10 else "medium"

        elif threshold is not None:
            thresh_pct = round(threshold * 100)
            why = (
                f"Rows where more than {thresh_pct}% of their columns were "
                f"empty were removed. These rows are too incomplete to contribute "
                f"reliable information to any analysis."
            )
            risk = (
                f"Keeping near-empty rows would mean the dataset includes records "
                f"that are mostly fabricated fill values, not real observations. "
                f"This degrades the accuracy of every aggregate metric."
            )
            method_why = (
                f"The {thresh_pct}% threshold means a row must have at least "
                f"{100 - thresh_pct}% of its values present to be kept. "
                f"This is a conservative threshold — only the most incomplete "
                f"rows are removed."
            )
            severity = "medium"

        else:
            why = "Rows with missing values in key columns were removed."
            risk = "Keeping incomplete rows would distort aggregated results."
            method_why = "Rows failing the completeness threshold were dropped."
            severity = "medium"

        return {
            "why": why,
            "risk": risk,
            "method_why": method_why,
            "severity": severity,
            "evidence_numbers": {
                "column": col,
                "threshold": threshold,
                "total_rows": total,
            },
        }


# Severity colours for the UI
SEVERITY_CONFIG = {
    "high":   {"color": "red",   "label": "High impact"},
    "medium": {"color": "amber", "label": "Medium impact"},
    "low":    {"color": "teal",  "label": "Low impact"},
}


reason_engine = ReasonEngine()